### PR TITLE
Update package deps

### PR DESCRIPTION
**Pull request by StephenHodgson**

### CODE REVIEW

**Comment by GoranPopovic1** [comment]
Hi there, 

Thanks for the PR, and sorry for a bit late response. This is something I tried before, it would be very helpful, but unfortunately it won't work, probably because it's not referencing the UPM branch of the package, it's just trowing an error: https://www.screencast.com/t/IIPyTOtI

**Comment by StephenHodgson** [comment]
@GoranPopovic1 what is your method of installation?

I'm using OpenUPM which manages the deps automatically. If you're using the git installer, you need to install the dep first manually.

**Comment by StephenHodgson** [comment]
I don't understand how pusher is optional. It's required to get events.

I may just do that and I'll ping scotty, since I think I've been asked to also implement the Unreal plugin as well.

**Comment by StephenHodgson** [comment]
Adding the package dep will simplify installation process for those using OpenUPM, which imho should be the suggested/default way to install the package, as git installation method is prone to breaking, and makes versioning more difficult.

**Comment by GoranPopovic1** [comment]
I agree that would simplify the installation process for the users using OpenUPM, but users using other two methods would still get errors if we add that dependency. Which might raise more issues on the Discord where we are supporting those users mainly.

We have a variety of users with different backgrounds, some of which are using Unity for the first time, and I would like to keep all 3 ways of installing the packages on the table, without any issues, at least without the ones we can sort out beforehand.

OpenUPM, to me, seems to be more for seasoned developers, since you have to install `npm` and run some commands in the terminal, and those developers shouldn't have much additional work before them, now that you submitted the Pusher package as well to OpenUPM. For an average user, it might be easier to just paste the link inside the Unity editor.

I'm open to discuss this next week further if needed, I still don't know in which capacity you will be working with us, but like I said, we can address this further next week, with my superior, with Scottie, and anyone else involved. We can give you access to this repo if needed, or you could create a fork which might go in some other direction. 

Have a nice weekend.

**Comment by StephenHodgson** [comment]
> OpenUPM, to me, seems to be more for seasoned developers, since you have to install npm and run some commands in the terminal

This is not true. You only need to add the scoped registry in the unity editor project settings.

**Comment by StephenHodgson** [comment]
Out of all 3 methods OpenUPM is the easiest and simplest of the installation methods.

**Comment by GoranPopovic1** [comment]
> This is not true. You only need to add the scoped registry in the unity editor project settings.

You are right, but I also see that OpenUPM recommended using a command-line tool: https://openupm.com/docs/#scoped-registry-and-command-line-interface 

And I still think that for the average user it will be easier to grasp the concept of adding a GitHub URL than the concept of scoped registries.

Also, the users who want to use OpenUPM can do it now nevertheless, thanks to Julien and you, so it's just a matter of preference at this point.

Anyway we have started to drift a bit from the original PR's purpose, I'm going to close it now, but like I mentioned, feel free to fork the repo if you think it should go in another direction.

Have a nice day.

**Comment by StephenHodgson** [comment]
>  feel free to fork the repo if you think it should go in another direction.

I really don't understand why you keep suggesting this, but I suppose I will 😏

**Comment by StephenHodgson** [comment]
well your wish came true: https://github.com/RageAgainstThePixel/com.rest.blockadelabs/releases/tag/1.0.0

**Pull request closed without merging**
